name: app_tcc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - imagem/DEV.png
  - imagem/Union.png
  - imagem/READS.png
  - imagem/dev reads.png
  - imagem/logo.png
  - imagem/img1.png
  - imagem/img2.png
  - imagem/img3.png
  - imagem/twitter.png
